namespace SharpTls.Quic;

// ============================================================================
// A4 TASK 14c - THE APPLICATION SEND PATH
// ============================================================================
//
// WHY THIS IS A SEPARATE FILE AND NOT MORE OF TlsQuicConnection.cs. The A4 plan's design
// constraints cap that file at 1000 code lines through task 14 and say, in the same list,
// "Task 14's new concerns do not go in this file. Short headers, 1-RTT sending,
// PATH_RESPONSE and streams are a different packet type and a different lifecycle from the
// handshake this file drives; they land in a sibling file."
//
// AND WHY IT IS A PARTIAL CLASS RATHER THAN A NEW TYPE. The same constraint list rejects
// splitting the connection into separate types, and gives the reason: Retry, close and idle
// timeout "mutate a dozen shared private fields ... and driving them into separate types
// would force every one of them `internal` - trading a long file for a wide mutable surface,
// which is the worse of the two". Everything below reads or writes exactly that state -
// _keys, _acks, _nextPacketNumber, _destinationConnectionId, PendingPathResponseData,
// _draining, _started, _disposed - so a second type would widen precisely the surface that
// argument protects. A partial class is the split that satisfies the file-size constraint
// WITHOUT paying that price, and the measurement the constraint names
// (`grep -vcE '^\s*(//|$)'`) is per file, so it is the honest split rather than a dodge.
//
// WHAT DOES NOT LIVE HERE. The receive side of 1-RTT - opening the packet, dispatching its
// frames, recording the PATH_CHALLENGE - is task 9a-ii's and 9b's and stays in
// TlsQuicConnection.cs beside every other frame it handles. Only the SEND direction moved.
//
// ============================================================================
// THE DELAYED-ACK TIMER: A DECISION, NOT A SILENCE
// ============================================================================
//
// A4's "Not in this phase" table carried the row "Delayed-ACK timer and max_ack_delay
// honouring for 1-RTT | A4-complete or A3 | s13.2.1 requires Initial and Handshake ACKs
// immediately, and minimal sends no 1-RTT data, so the timer has no customer yet". The
// second half of that reason stopped being true the moment this file existed, so the row is
// re-decided here rather than left standing on a premise this task removed.
//
// THE DECISION: ACKNOWLEDGE IMMEDIATELY, AT EVERY LEVEL, DELIBERATELY. No timer is added,
// and max_ack_delay is honoured by being beaten rather than by being scheduled against.
//
//   (a) IMMEDIATE SATISFIES THE MUST OUTRIGHT. s13.2.1: "An endpoint MUST acknowledge all
//      ack-eliciting Initial and Handshake packets immediately and all ack-eliciting 0-RTT
//      and 1-RTT packets within its advertised max_ack_delay." A delay of zero is within
//      every advertised value, so the deadline half of the MUST is met by construction and
//      cannot be missed by a scheduling bug. s13.2.1 states max_ack_delay as a CEILING - "an
//      endpoint promises to never intentionally delay acknowledgments of an ack-eliciting
//      packet by more than the indicated value" - not as a target to spend.
//   (b) THE COST s13.2.1 WARNS ABOUT CANNOT ARISE HERE. Its opening balances "frequent
//      feedback from a receiver" against "excessive load generated by a receiver that sends
//      an ACK frame in response to every ack-eliciting packet". This connection sends at
//      most one datagram per datagram received (SendAnswerAsync is called once per pump), so
//      the ACK rides in an answer that was being built anyway; delaying it would remove no
//      packet from the wire, only add latency. The related MUST - "an endpoint MUST NOT send
//      more than one such packet in response to receiving an ack-eliciting packet" - is met
//      by the same one-answer-per-pump shape.
//   (c) A TIMER IS AN ARCHITECTURE CHANGE, NOT A TUNING KNOB. TlsQuicConnection's remarks
//      open with "ONE LOOP, ONE THREAD OF CONTROL" and name it as what satisfies
//      CustomTlsQuicClient's and TlsQuicPacketReceiver's shared-state requirements. A
//      delayed ACK has to fire without a datagram to trigger it, which means either a second
//      thread of control or a timeout woven into the receive await - the first breaks that
//      invariant, and the second is loss-recovery scheduling, which is A3's.
//
//      AND A3 HAS NOW BUILT IT, SO HALF OF (c) IS SPENT. Task A3-5 wove the timeout into the
//      receive await, on the injected TimeProvider, without a second thread: EarliestDeadline
//      in TlsQuicConnection.cs picks the nearest of the handshake deadline, RFC 9000 s10.1's
//      idle timeout and RFC 9002 A.8's loss detection timer, and a wake on the third returns
//      an empty receive result so the pump runs its ordinary send pass with no datagram
//      received. WHAT SURVIVES OF (c) IS THE HALF THAT MATTERED: it is an architecture
//      change, it was sequenced alone for exactly that reason, and it was not A4's to make.
//      What no longer follows from (c) is that the mechanism is unavailable.
//   (d) IT COSTS NOTHING WE MEASURE. The ack_delay this connection reports is already zero
//      for the reason PumpOnceAsync's "ONE INSTANT PER PUMP" note gives, and with an
//      immediate ACK that zero is EXACT rather than merely safe in one direction.
//
// (The four points are lettered rather than numbered so that this file's ledger greps, which
// anchor on `^// +[0-9]+\. `, cannot match them.)
//
// SO THE ROW IS NOT DEFERRED, IT IS CLOSED FOR A4: the timer is not missing work, it is work
// this shape does not need. A4-complete owns it again only if it adds a send path that runs
// between received datagrams often enough for batching to remove packets rather than add
// delay - which is the same condition under which s13.2.1's balance argument starts to bite.
//
// THAT CONDITION IS NOW SATISFIED, AND THE ROW IS REOPENED RATHER THAN LEFT STANDING ON A
// PREMISE THAT HAS GONE. A3-5's wake-on-deadline entry IS a send path that runs between
// received datagrams: PumpOnceAsync now reaches SendAnswerAsync with no datagram received at
// all, so (b)'s "this connection sends at most one datagram per datagram received" has stopped
// being true of it. WHAT THAT DOES AND DOES NOT DECIDE. It does not make an immediate ACK
// wrong - a delay of zero still satisfies s13.2.1's MUST outright, and (a) and (d) are
// untouched. It removes the ARGUMENT in (b) and the OBSTACLE in (c), which together were the
// whole reason the question was closed rather than weighed. Weighing it is
// TlsQuicRecoverySpec.AckPolicy - knob 12 - and A3-12's readout, and it is deliberately NOT
// A3-5's: the timer weave was sequenced alone precisely so that a failure after it is
// attributable to the weave and not to an ACK policy bundled with it. Until a knob says
// otherwise, this connection still acknowledges immediately at every level.
//
// AND A3-11 CONSIDERED IT AND DECLINED IT, WHICH IS RECORDED HERE RATHER THAN LEFT AS A THIRD
// SILENCE. A3-11 added the fourth entry to EarliestDeadline's table, so the mechanism a delayed
// ACK needs now exists twice over and the OBSTACLE in (c) is gone for good. The reason knob 12
// is still unread is not availability, it is that it is a DIFFERENT SENTENCE. RFC 9002 s7.7's
// only word about acknowledgements is lines 353-355 - "packets containing only ACK frames
// SHOULD therefore not be paced" - which is a rule about NOT delaying them, and this task
// implements it structurally by never consulting the pacer on an ACK-only pass. Wiring knob 12
// would DELAY them, on RFC 9000 s13.2.1's authority and not RFC 9002 s7.7's, and it changes how
// many ACK packets leave rather than when a data packet does. Bundling the two would have made
// a failure in either attributable to neither - which is (c)'s own argument, one task later.
// The knob is therefore read by nothing ON THIS PATH, and that is a decision with a reason
// rather than a gap: it belongs to whoever owns s13.2.1's timer.
//
// AND TASK A3-13 TOOK IT, which is recorded here because this paragraph is the reason it was
// A3-13's to take and not A3-11's. The reader is TlsQuicAckTracker.IsWithheldAt, and the
// mechanism that releases a held ACK is TlsQuicConnection's fourth TlsQuicDeadlineKind,
// DelayedAck. NOTHING IN THIS FILE CHANGED FOR THAT, and the split above is why: what A3-13
// delays is the ACK itself, on s13.2.1's authority, and what this path still declines to do is
// consult the pacer on an ACK-only pass, on s7.7's. Two sentences, two owners, two tasks.
//
// ONE CONSEQUENCE IS A KNOWN CEILING RATHER THAN AN OMISSION, and TlsQuicAckTracker carries it
// in full next to IsWithheldAt: because the 1-RTT send path reaches TryBuildAck through the
// NON-force overload, a held ACK is not picked up by a data packet that happens to leave inside
// the 25 ms bound. Routing it through `force` would change the SHIPPED DEFAULT's emitted bytes,
// and default parity outranks a SHOULD whose bound is already met.
//
// The value the knob ships with is a separate question from whether anything reads it, and that
// question is still open: A3-12's readout must render it as UNVERIFIED either way.

// ============================================================================
// THE MUTATION LEDGER
// ============================================================================
//
//   ROWS BELOW                   13  = numbered 1-13 with no gaps
//   KILLED WHEN FIRST RUN        10  = 13 rows, less 0 [WAS-SURVIVOR] and 3 [SURVIVED]
//   SURVIVED, THEN FIXED OR       0
//     WITNESSED
//   SURVIVING STILL               3  = rows 3, 4, 9, every one of them classified below
//
// Three greps, all anchored to a numbered row so that THESE lines, which also carry the
// markers, do not match themselves. Run from this file's directory:
//   `grep -cE '^// +[0-9]+\. ' TlsQuicApplicationSendPath.cs`                    must return 13
//   `grep -cE '^// +[0-9]+\..*\[WAS-SURVIVOR\]' TlsQuicApplicationSendPath.cs`   must return 0
//   `grep -cE '^// +[0-9]+\..*\[SURVIVED\]' TlsQuicApplicationSendPath.cs`       must return 3
//
// ROW 13 IS TASK 14e's AND WAS MEASURED AT ITS OWN GATE - 1303 cases - not at 14c's; the two
// figures are not comparable and are labelled rather than averaged. Rows 1-12 below carry 14c's.
//
// All twelve of 14c's were run against task 14c's 1136-test gate, and re-run against it after the last
// test of that task landed rather than left at the figures the first pass produced - which moved
// four of them. Counts are per xUnit CASE, so a two-row Theory failing in both rows counts 2. The mutations that edit
// TlsQuicConnection.cs are in ITS ledger (its rows 19, 20, 68 and 89 were re-run and its rows
// 90-92 are new), and the two that edit LoopbackQuicPeer.cs are in its. Where a row says ONLY,
// that test was the entire failure set.
//
//    1. The PATH_RESPONSE frame never added       ONLY both rows of APathChallengeIsAnsweredWithAPathResponseInAOneRttPacket
//    2. PendingPathResponseData never cleared     ONLY both rows of APathChallengeIsAnsweredWithAPathResponseInAOneRttPacket
//    3. The Application write-key check removed   [SURVIVED] 0 of 1136 - unreachable by construction
//    4. That check moved after the frame build    [SURVIVED] 0 of 1136 - unreachable by construction, and for the same reason as row 3
//    5. ShortHeaderPlan carries the connection's Version  18 tests
//    6. ShortHeaderPlan's destination is our own Source Connection ID  6 tests
//    7. The Application packet number never advances  ONLY AOneRttPacketThisConnectionSentIsAcknowledgedByTheLoopbackPeer
//    8. The key phase bit set against the installed phase  3 tests
//    9. LargestAcknowledged not reported at Application  [SURVIVED] 0 of 1136 - vacuous
//   10. The spin bit set                          ONLY AOneRttPacketThisConnectionSentIsAcknowledgedByTheLoopbackPeer
//   11. SendPendingAsync's EnsureSendable dropped  2 tests
//   12. AckLeadsInPacket ignored in the 1-RTT packet  ONLY the ackLeads:false row of APathChallengeIsAnsweredWithAPathResponseInAOneRttPacket
//   13. task 14e's pending STREAM frames never reach the packet  3 tests
//
// ROW 13 IS TASK 14e's WHOLE FOOTPRINT IN THIS FILE - four code lines - and its three are the
// only tests in the tree that watch a STREAM frame leave. It is one row and not two because
// there is nothing to separate: the frames are queued by TlsQuicStreamSet and taken here, so a
// take that never happens and a take whose result is dropped are the same edit. The rest of
// the task is in TlsQuicStreams.cs's own ledger, rows 1-42.
//
// ROWS 3 AND 4 ARE ONE ARGUMENT, AND THE SECOND IS WHY THE FIRST IS NOT ENOUGH ON ITS OWN.
// Row 3 deletes the write-key check; row 4 keeps it and moves it BELOW the frame build, which
// is where the PATH_RESPONSE record would already have been cleared. Both survive, and both
// survive for the same reason: the check never returns false in any state this phase can
// reach, because every frame the method can build exists only because a 1-RTT packet was
// OPENED, and the Application read keys that requires arrive from the same completion result
// as the write keys. SO THE ORDERING IN THE SOURCE IS A CLAIM ABOUT AN UNREACHABLE STATE, and
// it is written down as one rather than asserted as load-bearing - which is the mistake row 71
// of TlsQuicConnection.cs's ledger records. A test for either would have to install one
// direction of the Application keys and not the other, which no path here does.
//
// ROW 9 IS VACUOUS, NOT MERELY UNWITNESSED, AND THAT IS WHY IT HAS NO TEST. RFC 9000
// Appendix A.2 uses Largest Acknowledged to bound the encoded packet number length from below,
// and TlsQuicConnection.cs's row 23 is the long-header witness for exactly that. At the
// Application level the mutant's value and the original's are the SAME value in every
// reachable state: this phase sends at most one 1-RTT packet, and the plan for it is built
// before any ACK covering the Application space can have arrived, so _acks.LargestAcked is
// null there whatever this line says. It stops being vacuous the moment a second 1-RTT packet
// is sent after a peer ACK, which is subsystem C's first stream write.
//
// ROW 6 KILLS ONLY SIX OF 1136, AND THE NUMBER IS THE POINT. A short header carrying the wrong
// Destination Connection ID is still a well-formed packet - RFC 9000 s17.3.1 gives the field no
// length prefix, so a peer parses it by the length it EXPECTS and simply fails to open what it
// finds. It is caught by the tests that make a peer OPEN one of ours and by the fingerprint
// snapshot, and by nothing else in the tree; the handshake itself never notices, because by the
// time a 1-RTT packet exists the handshake is over. Compare row 5, which kills 18: a Version
// field on a short-header plan is rejected by TlsQuicPacketBuilder before any byte is written,
// so it fails loudly inside our own process. The same wrong idea costs three times as many
// tests when a validator sees it as when only a peer does.

internal sealed partial class TlsQuicConnection
{
    /// <summary>The largest packet number the peer has acknowledged in the packet number
    /// space (RFC 9000 s12.3) that <paramref name="level"/> belongs to, or
    /// <see langword="null"/> if it has acknowledged nothing there.</summary>
    /// <remarks>The witness for a 1-RTT packet that a peer actually acknowledged: nothing
    /// else this connection exposes moves when an Application-space ACK arrives.</remarks>
    internal ulong? LargestAcknowledged(TlsQuicEncryptionLevel level) => _acks.LargestAcked(level);

    // ========================================================================
    // TASK A3-11 - RFC 9002 s7's SEND GATE, AND THE THREE THINGS IT MUST LET PAST
    // ========================================================================
    //
    // THE HANDOVER THIS CLOSES, IN A3-8's OWN WORDS: "s7's MUST NOT send a packet if it would
    // cause bytes_in_flight to be larger than the congestion window still doesn't gate NEW
    // data. The window is live and every signal reaches it; the gate needs the probe/recovery
    // exceptions threaded through TlsQuicApplicationSendPath.cs". TlsQuicLossDetection.cs's own
    // closing note says the same thing from the other end - "BuildAnswerDatagram and
    // TryBuildApplicationPacket still build without asking".
    //
    // THE SENTENCE, rfc9002-section7-congestion-control.txt lines 46-49, verbatim and complete
    // including the clause that is usually dropped:
    //
    //     An endpoint MUST NOT send a packet if it would cause bytes_in_flight (see
    //     Appendix B.2) to be larger than the congestion window, unless the packet is sent on
    //     a PTO timer expiration (see Section 6.2) or when entering recovery (see
    //     Section 7.3.2).
    //
    // A GATE WITHOUT THOSE TWO EXCEPTIONS IS NOT A STRICTER IMPLEMENTATION OF THIS SENTENCE,
    // IT IS A DEADLOCK. The window closes when bytes are in flight; the bytes leave flight when
    // they are acknowledged, declared lost, or discarded; and a connection whose peer has gone
    // silent learns none of those without sending something. The PTO probe is the thing that
    // makes it learn. Block the probe and the window can never reopen - which is the exact
    // stall RFC 9000 s8.1's anti-deadlock probe exists to break, and which task A3-7 closed.
    //
    // THE FOUR CLASSES OF SEND, AND WHICH SIDE OF THE GATE EACH IS ON:
    //
    //   1. PTO PROBES - EXEMPT, s7's first exception and s7.5 lines 195-196: "Probe packets
    //      MUST NOT be blocked by the congestion controller. A sender MUST however count these
    //      packets as being additionally in flight". EXEMPT BY CONSTRUCTION AND NOT BY A FLAG:
    //      SendOwedProbeAsync and TryBuildProbeDatagram never call this method, so there is no
    //      argument a caller could pass wrongly. The second half of s7.5 was already satisfied
    //      before this task - the probe's datagram goes through RetainSentPackets and
    //      OnPacketSent like every other, so its bytes ARE counted and the window may legally
    //      go negative-headroom afterwards, which s7.5's last sentence explicitly anticipates.
    //
    //   2. THE ONE PACKET ON ENTERING RECOVERY - EXEMPT, s7's second exception, pointing at
    //      s7.3.2 lines 147-153: "Implementations MAY reduce the congestion window immediately
    //      upon entering a recovery period or use other mechanisms, such as Proportional Rate
    //      Reduction [PRR], to reduce the congestion window more gradually. If the congestion
    //      window is reduced immediately, A SINGLE PACKET CAN BE SENT PRIOR TO REDUCTION. This
    //      speeds up loss recovery if the data in the lost packet is retransmitted". That is
    //      B.6's undefined MaybeSendOnePacket, and the controller's own remarks record that it
    //      "is not implemented and the window is reduced immediately, which is the same lines'
    //      first alternative" - the alternative whose next sentence GRANTS this packet. So the
    //      exemption is available to this build precisely because A3-9 reduced immediately.
    //
    //      HOW IT IS DETECTED WITHOUT WIDENING THE SEAM, WHICH IS THE DESIGN CALL HERE.
    //      ITlsQuicCongestionController's CanSend remarks already settle where the exceptions
    //      live: "The two exceptions are the CALLER's ... Putting the exceptions here would
    //      mean this method sometimes answers a question it was not asked". So no eighth member
    //      was added. The signal used instead is one every controller has and the seam already
    //      exposes: CongestionWindowBytes going DOWN. s7.3.2's reduction is the only thing that
    //      lowers a NewReno window apart from s7.6.2's collapse, and a CUBIC or BBR controller
    //      that lowers its window has by the same token entered its own recovery - so the
    //      detection is as portable as the seam is, which a type test on NewReno would not have
    //      been. It grants ONE packet, because s7.3.2 says "a single packet".
    //
    //      s7.6.2's COLLAPSE ALSO LOWERS THE WINDOW AND THEREFORE ALSO GRANTS ONE. That is
    //      named rather than special-cased: B.8 runs the congestion event and the persistent-
    //      congestion collapse in one body, s7.3.2's grant is a MAY in both readings, and one
    //      extra packet at the moment a blackout is declared is the same single packet s7.3.2
    //      licenses - it does not accumulate, because the exemption is consumed on use.
    //
    //   3. ACK-ONLY CONTENT - NEVER GATED, AND NOT AS A FAVOUR. RFC 9002 B.2 lines 507-509:
    //      "Packets only containing ACK frames do not count toward bytes_in_flight", so such a
    //      packet cannot cause bytes_in_flight to be larger than anything and s7's sentence has
    //      no purchase on it. s7.7 lines 353-355 say the same for the pacer: "packets
    //      containing only ACK frames SHOULD therefore not be paced". BOTH ARE STRUCTURAL HERE:
    //      this method is consulted only where the send path is about to add IN-FLIGHT frames,
    //      so a pass whose only output is an ACK never reaches it, and the ACK leaves on time.
    //      That is also the second limb of the anti-deadlock argument - a fully closed window
    //      still acknowledges, so the peer's own window keeps moving.
    //
    //   4. CRYPTO FROM THE TLS ENGINE - NOT GATED, AND THIS IS A CEILING RATHER THAN A CLAIM
    //      OF CONFORMANCE. TlsQuicCryptoDataEvent hands over the only copy of its bytes -
    //      Finding 1 - and BuildAnswerDatagram's caller disposes every result on the way out of
    //      the pump, so a pass that declined to put a CRYPTO frame in a packet would DESTROY
    //      it, not defer it. Gating it needs a send queue for handshake bytes, which is a
    //      feature and not a guard. The exposure is bounded and small: the client's whole
    //      handshake flight is one or two datagrams against an initial window of ten, so the
    //      window cannot close on a path that has only ever sent CRYPTO. Recorded here so that
    //      the next reader does not mistake the absence for an oversight; a A4-era send queue
    //      is what would close it.
    //
    // WHAT IS ON THE GATED SIDE, THEN: A3-8's repair queues (already, since A3-8 - see
    // TakeRepairsInto, which asks CanSend and leaves a refused repair OWED) and this task's
    // addition, the 1-RTT frames TlsQuicStreamSet holds - which is both new stream data and the
    // 1-RTT repairs, since TakePendingFrames drains the two together. THAT IS THE BULK SENDER.
    // Everything a caller of this library can generate in quantity goes through that one queue.
    //
    // A REFUSED SEND IS DEFERRED AND NEVER DROPPED, which is what makes the gate safe to put
    // in front of a queue at all: TakePendingFrames is simply not called, so the frames stay
    // queued in their own order and the next pass offers them again.
    //
    // THE SIZE THIS ASKS ABOUT IS max_datagram_size AND THAT IS AN OVER-ESTIMATE, DELIBERATELY
    // IN THE OPPOSITE DIRECTION FROM A3-8's. TakeRepairsInto passes the sum of the repairs'
    // payloads and its own remarks call that "a lower bound"; a lower bound admits a packet at
    // the boundary that a byte-exact gate would refuse. This asks for a whole datagram, because
    // the quantity s7 is written in IS the datagram - s7.2's initial window is ten of them and
    // its minimum window is two - and because the exact size is TlsQuicPacketBuilder's and does
    // not exist until after the build, by which time the packet number is spent and the frames
    // are taken. Over-estimating can only ever refuse a send s7 would have permitted, which is
    // the direction a MUST NOT should be wrong in.

    /// <summary>RFC 9002 s7's send gate and s7.7's pacer, asked once, before anything that
    /// would put bytes in flight is taken out of a queue.</summary>
    /// <remarks>See this file's A3-11 block for the sentence, the two exceptions, and the four
    /// classes of send.</remarks>
    /// <param name="now">The pump's instant.</param>
    /// <returns>True when in-flight frames may be added to this pass's packet.</returns>
    private bool SendGateAdmits(DateTimeOffset now)
    {
        var bytes = _options.Spec.PaddingTarget;
        var controller = Congestion;
        var window = controller.CongestionWindowBytes;

        // s7's SECOND EXCEPTION, ARMED. The comparison is against the window as it stood the
        // last time this gate ran, so a reduction that happened between two send passes is seen
        // exactly once however many packets were sent in between. First call arms the baseline
        // and grants nothing, which is right: a fresh controller has entered no recovery period.
        if (_windowAtLastGate is { } previous && window < previous)
        {
            _recoveryExemptionOwed = true;
        }

        _windowAtLastGate = window;

        var exempt = false;
        if (!controller.CanSend(bytes))
        {
            if (!_recoveryExemptionOwed)
            {
                SendsRefusedByCongestionWindow++;
                return false;
            }

            exempt = true;
        }

        // s7.7. The rate is read live off the same controller the gate just asked, so a window
        // that moved moves the spacing with it, and the smoothed RTT is the estimator's rather
        // than a second copy.
        if (!Pacer.TryTake(bytes, now, window, _acks.SmoothedRtt))
        {
            SendsDeferredByPacer++;
            return false;
        }

        // s7.3.2's "a single packet can be sent prior to reduction", SPENT ONLY WHEN THE PACKET
        // ACTUALLY LEAVES - which is why the pacer is asked first and this line is last.
        // Consuming it above, before s7.7 had its say, burned a permission on a pass that then
        // did not send: the release pass that followed would find the window still shut, the
        // exemption already gone, and the one packet s7.3.2 grants never sent at all. That is
        // not a conformance failure - the grant is a MAY - but it is the grant not taken, and
        // its whole purpose is to "speed up loss recovery if the data in the lost packet is
        // retransmitted".
        if (exempt)
        {
            _recoveryExemptionOwed = false;
            RecoveryWindowExemptionsUsed++;
        }

        return true;
    }

    private long? _windowAtLastGate;
    private bool _recoveryExemptionOwed;
    private TlsQuicPacer? _pacer;

    /// <summary>This connection's RFC 9002 s7.7 pacer, built from knobs 14 and 15.</summary>
    /// <remarks>CONSTRUCTED ON FIRST USE, for the reason <c>Congestion</c> gives about its own:
    /// a connection that is built and never started should run nothing the spec configured.
    /// </remarks>
    internal TlsQuicPacer Pacer =>
        _pacer ??= new TlsQuicPacer(_options.Spec.Recovery, _options.Spec.PaddingTarget);

    /// <summary>How many send passes RFC 9002 s7's congestion window has refused.</summary>
    /// <remarks>THE WITNESS THAT THE GATE ENGAGED. A transfer that completes completes with no
    /// gate at all, so a test that only watched the transfer would score a build that never
    /// asked. Counts refusals, not questions: an admitted send does not move it.</remarks>
    internal int SendsRefusedByCongestionWindow { get; private set; }

    /// <summary>How many send passes RFC 9002 s7.7's pacer has held back.</summary>
    /// <remarks>The same witness for the pacer, and the reason the live tests can tell pacing
    /// on from pacing off without measuring wall-clock time.</remarks>
    internal int SendsDeferredByPacer { get; private set; }

    /// <summary>How many times RFC 9002 s7's "or when entering recovery" exception has carried
    /// a send past a closed window.</summary>
    internal int RecoveryWindowExemptionsUsed { get; private set; }

    /// <summary>RFC 9002 s7.7's release instant, for
    /// <c>TlsQuicConnection.EarliestDeadline</c>'s earliest-of table.</summary>
    /// <remarks>NULL WHENEVER THE PACER HAS NOT DEFERRED, so the table is unchanged for every
    /// connection that does not pace and for every pass a pacing connection admits - which is
    /// what keeps a build with pacing off byte-for-byte and instant-for-instant identical to
    /// the build before this task.</remarks>
    internal DateTimeOffset? PacingReleaseAt => _pacer?.ReleaseAt;


    /// <summary>Sends whatever is pending without waiting for a datagram to arrive first,
    /// and reports whether anything went out.</summary>
    /// <remarks>
    /// <para>AN ADDITIONAL ENTRY, NOT A REPLACEMENT FOR <see cref="PumpOnceAsync"/>. The
    /// receive-driven loop is still what drives the handshake; this exists because from
    /// 1-RTT onwards the client is the one with something to say first - subsystem C opens an
    /// HTTP/3 control stream and sends SETTINGS before the server has said anything - and a
    /// pump that can only answer cannot do that.</para>
    /// <para>ONE LOOP, ONE THREAD OF CONTROL still holds: this is a call the same caller
    /// makes on the same thread between pumps, not a second pump running beside the first.
    /// </para>
    /// </remarks>
    /// <returns><see langword="true"/> if a datagram was sent.</returns>
    internal async ValueTask<bool> SendPendingAsync(CancellationToken cancellationToken = default)
    {
        EnsureSendable();

        // NO CRYPTO EVENTS, because nothing was received to produce any. Everything else
        // BuildAnswerDatagram does - the pending ACKs at each level, the PATH_RESPONSE - is
        // read from state that is already there.
        return await SendAnswerAsync([], _options.TimeProvider.GetUtcNow(), cancellationToken)
            .ConfigureAwait(false);
    }

    // The three preconditions both entry points share, lifted out of PumpOnceAsync so that
    // one gate guards both rather than two copies drifting apart. The messages are unchanged
    // and the tests that pin them are unchanged with them.
    private void EnsureSendable()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        if (!_started)
        {
            throw new InvalidOperationException("Start the connection before pumping it.");
        }
        if (_draining)
        {
            // RFC 9000 s10.2.1 and s10.2.2, the two states this one flag stands for. A4-minimal
            // implements them only as far as "stop sending, stop delivering": there is no timer
            // holding the state for "at least three times the current PTO", because A3 owns the
            // PTO and there is nothing here to hold state FOR - a one-shot attempt has no later
            // packet to attribute. s10.2.1's "sends a packet containing a CONNECTION_CLOSE frame
            // in response to any incoming packet" is deliberately not implemented for the same
            // reason it is rate-limited there: it answers packets, and this connection has
            // stopped reading them.
            throw new InvalidOperationException(
                "This connection is closing or draining (RFC 9000 s10.2), so it neither sends "
                    + "nor delivers. A new attempt is a new connection.");
        }
    }

    /// <summary>Builds the one 1-RTT packet this connection may have to send, or reports that
    /// there is nothing to put in one.</summary>
    /// <remarks>
    /// <para>BUILT AFTER THE LEVEL LOOP RATHER THAN INSIDE IT, AND THAT IS RFC 9000 s12.2
    /// RATHER THAN A PREFERENCE: "packets with a short header (Section 17.3) do not contain a
    /// Length field and so cannot be followed by other packets in the same UDP datagram."
    /// <see cref="TlsQuicDatagramBuilder"/> enforces it and would throw on a datagram that put
    /// this packet anywhere else. The spec's <c>CoalesceAscendingByLevel</c> knob orders the
    /// LONG-header packets - which is the dimension a fingerprint can see - and with it false
    /// the Application level comes FIRST in the descending list, so building this packet in
    /// the loop would hand the datagram builder an illegal order on any answer that also
    /// carried an Initial or Handshake packet. THAT IS REACHABLE FROM A CONFORMING PEER: a
    /// server that retransmits its ack-eliciting Handshake flight coalesced with a 1-RTT
    /// packet leaves this connection owing an ACK at two levels in one answer. Position is
    /// therefore not a knob here, and this method's placement is what makes it unreachable
    /// rather than a guard that has to fire.</para>
    /// <para>NOT async, and it cannot be: <c>TlsQuicWriteKeyMaterial</c> is a ref struct, so
    /// key material never lives in an async state machine.</para>
    /// </remarks>
    private bool TryBuildApplicationPacket(DateTimeOffset now, out TlsQuicPacketToSend packet)
    {
        packet = default;

        // THE KEY CHECK COMES FIRST, AND UNLIKE THE ANSWER LOOP'S IT IS NOT A THROW.
        // BuildAnswerDatagram throws when a level has frames and no write keys because the
        // frames there are CRYPTO - the TLS engine's output, which arriving at a level this
        // connection cannot protect is a sequencing bug worth stopping for. The frames here
        // are ACK and PATH_RESPONSE, both of which are ours to withhold, and RFC 9001 s4.9
        // makes "no keys at this level" the ordinary state rather than an error. s13.2.1's
        // own exception says the same thing in the ACK's case: "an endpoint might not have
        // packet protection keys ... It might therefore buffer them and acknowledge them when
        // the requisite keys become available."
        //
        // AND IT COMES FIRST SO THAT PendingPathResponseData IS NOT CLEARED BY A PACKET THAT
        // WAS NEVER BUILT. RFC 9000 s19.17's MUST is to answer the challenge; dropping the
        // eight bytes on the way to discovering we could not send would turn a deferral into
        // a violation.
        //
        // BOTH THE CHECK AND ITS POSITION ARE UNREACHABLE TODAY AND DELIBERATELY UNWITNESSED,
        // AND THAT IS MEASURED RATHER THAN ASSUMED - mutation rows 3 and 4 both survive the
        // whole gate. Every frame built below exists only because a 1-RTT packet was OPENED,
        // which needs Application READ keys, and CustomTlsQuicClient raises both Application
        // traffic secrets from the one completion result that PumpOnceAsync installs before it
        // sends. So this branch is never taken and the paragraph above is a claim about a
        // state that cannot arise; it is kept because the state becomes reachable the moment
        // anything installs the two directions apart, and it is labelled rather than asserted
        // to be load-bearing.
        if (!_keys.TryGetWriteKeys(TlsQuicEncryptionLevel.Application, out var keys, out _))
        {
            return false;
        }

        var frames = new List<TlsQuicFrame>();

        // The ACK's position is the spec's here for the same reason it is in
        // BuildAnswerDatagram - a knob the connection fixes is a knob task 11 cannot report.
        var hasAck = TryBuildAckFrame(TlsQuicEncryptionLevel.Application, now, out var ack);
        if (hasAck && _options.Spec.AckLeadsInPacket)
        {
            frames.Add(ack);
        }

        if (PendingPathResponseData is { } challenge)
        {
            // RFC 9000 s19.17: "The recipient of this frame MUST generate a PATH_RESPONSE
            // frame (Section 19.18) containing the same Data value." s19.18 makes the two
            // frames' formats identical, so the recorded eight bytes go back out unchanged -
            // re-deriving them would be a second transcription of a value the peer chose.
            //
            // s12.4 Table 3 gives PATH_RESPONSE the row "___1", a 1-RTT packet and nothing
            // else, which is why task 9b could record this and not send it and why the answer
            // is built here rather than beside the record.
            frames.Add(new TlsQuicFrame
            {
                RawType = (ulong)TlsQuicFrameType.PathResponse,
                Data = challenge,
            });

            // CLEARED, AND NOT RETRANSMITTED IF THIS DATAGRAM IS LOST - RFC 9000 s13.3's
            // frame-by-frame loss rules put PATH_RESPONSE among the frames that are not
            // resent. NOT QUOTED, BECAUSE s13.3 IS NOT IN THIS REPO'S REFERENCE CAPTURES:
            // rfc9000-section13-packetization-and-ack-generation.txt stops inside s13.2, so
            // this citation is weaker than the ones around it and is marked as such rather
            // than dressed up with a quotation nobody here can check. The behaviour is also
            // what A4-minimal would do anyway: it has no retransmission at all (that is A3's),
            // so a lost answer is the peer's PATH_CHALLENGE to repeat.
            PendingPathResponseData = null;
        }

        // TASK 14e's STREAM FRAMES, AFTER THE PATH_RESPONSE AND BEFORE THE TRAILING ACK. RFC
        // 9000 s12.4 Table 3 gives STREAM the row "__01", so a 1-RTT packet is where they
        // belong, and TlsQuicFrameLegality.Permits gates that in the builder. The position is
        // NOT a fingerprint knob claiming to be one: AckLeadsInPacket decides whether the ACK
        // leads or trails, and these sit inside whichever bracket that leaves, so both rows of
        // the knob still put the ACK where the knob says.
        //
        // _streams RATHER THAN Streams, because the property builds the set from the peer's
        // budget on first touch and would throw here on a connection whose parameters have not
        // arrived. Nothing is pending on a connection that never opened a stream.
        //
        // A3-11's GATE, AND THIS IS THE LINE A3-8's HANDOVER NAMED. TakePendingFrames drains
        // both this stream set's 1-RTT repairs and its new data, so RFC 9002 s7's MUST NOT and
        // s7.7's pacer are asked once, here, ahead of the take rather than after it - a refused
        // pass leaves every frame queued in its own order and offers it again next time.
        // See SendGateAdmits above for the two exceptions and for what is deliberately not
        // gated.
        //
        // THE ORDER OF THE TWO CONDITIONS IS LOAD-BEARING. HasPendingFrames comes FIRST so that
        // a connection with nothing to send never consults the gate at all: asking would spend
        // the pacer's credit on an empty pass and, worse, would arm a pacing deadline for a
        // datagram that does not exist. It also keeps every ACK-only pass off this path
        // entirely, which is s7.7 lines 353-355 and B.2 lines 507-509 - see the block above.
        if (_streams is { } streams && streams.HasPendingFrames && SendGateAdmits(now))
        {
            // RFC 9000 s14.2: "All QUIC packets that are not sent in a PMTU probe SHOULD be
            // sized to fit within the maximum datagram size to avoid the datagram being
            // fragmented or dropped." THIS LINE IS THAT SENTENCE. Until it existed the take
            // was unbounded - `frames.AddRange(streams.TakePendingFrames())` - and a request
            // body arrived as one STREAM frame in one datagram of whatever size the body
            // happened to be. A 32 KB body produced a 32837-byte datagram, which a DF-set
            // IPv4 socket refuses outright with SocketError.MessageSize.
            //
            // WHAT IS ALREADY IN `frames` IS CHARGED FOR, not assumed away: an ACK and a
            // PATH_RESPONSE may precede the stream data, and both are measured with the same
            // encoder that will write them rather than estimated.
            streams.DatagramPayloadBudget = DatagramPayloadBudget;

            var spent = OneRttPacketOverhead;
            foreach (var already in frames)
            {
                spent += TlsQuicFrames.MeasureFrame(_frameMeasureScratch, already);
            }

            frames.AddRange(streams.TakePendingFrames(DatagramPayloadBudget - spent));
        }

        if (hasAck && !_options.Spec.AckLeadsInPacket)
        {
            frames.Add(ack);
        }

        if (frames.Count == 0)
        {
            return false;
        }

        packet = new TlsQuicPacketToSend
        {
            Plan = ShortHeaderPlan(),
            Frames = frames,
            PacketProtectionCipher = keys.PacketCipher,
            Key = keys.Key.ToArray(),
            Iv = keys.Iv.ToArray(),
            HeaderProtectionCipher = keys.HeaderCipher,
            HeaderProtectionKey = keys.HeaderProtectionKey.ToArray(),
        };
        return true;
    }

    // RFC 9000 s17.3.1's 1-RTT packet. A null Type is what TlsQuicPacketBuilder reads as
    // "short header" (A4 task 14b), and the four fields the long header has and this one does
    // not - Version, Source Connection ID, Token, Length - are set to their absent values
    // rather than left to the spec's knobs, because TlsQuicPacketBuilder.ValidateShortHeaderP
    // lan rejects a plan that asks for a field s17.3.1 does not write.
    private TlsQuicPacketPlan ShortHeaderPlan() => new()
    {
        Type = null,
        Version = 0,
        DestinationConnectionId = _destinationConnectionId,
        SourceConnectionId = default,
        Token = default,
        LengthVarintWidth = TlsQuicVarintWidth.Minimal,

        // RFC 9000 s12.3 gives 0-RTT and 1-RTT one packet number space, which is the space
        // this counter's Application slot is; s12.3 also forbids reusing a number in it.
        PacketNumber = _nextPacketNumber[(int)TlsQuicEncryptionLevel.Application]++,
        PacketNumberEncodedLength = _options.Spec.PacketNumberEncodedLength,
        LargestAcknowledged = _acks.LargestAcked(TlsQuicEncryptionLevel.Application),

        // RFC 9001 s5.4: both are protected bits of the short header. KEY PHASE FOLLOWS THE
        // INSTALLED PHASE, and it is now a value rather than a constant: RFC 9001 s6 toggles
        // it on every key update and TlsQuicKeySet owns which generation the write keys are
        // at. This line USED TO READ `KeyPhase = false` with the reason "TlsQuicKeySet
        // installs every level at phase 0 - key update is out of scope for this phase"; that
        // reason is gone, and reading the phase from the key set is what keeps the bit and the
        // keys from ever disagreeing.
        //
        // SPIN BIT: RFC 9000 s17.4's latency spin bit is a passive-measurement aid, not part
        // of packet processing - a constant zero is the disabled reading, it is what the one
        // other short header in this tree (LoopbackQuicPeer's HANDSHAKE_DONE packet) already
        // writes, and it is not a dimension the fingerprint capture records. The section is
        // cited rather than quoted: rfc9000-packet-formats-and-pn-pseudocode.txt truncates
        // s17.4 mid-sentence, so the endpoint-behaviour paragraph is not checkable from this
        // repo's captures. It is not a TlsQuicConnectionSpec knob, so it is not claimed to be
        // one.
        SpinBit = false,
        KeyPhase = ProtectOneMoreApplicationPacket(),
    };

    // RFC 9001 s6.6: "Endpoints MUST count the number of encrypted packets for each set of
    // keys." Counted HERE, in the one method every 1-RTT packet's plan comes from - all three
    // call sites reach it, and it is already the single place the Application packet number is
    // spent, so a packet that is built and never sent still consumes both.
    //
    // RETURNING THE KEY PHASE IS WHAT MAKES THE COUNT UNSKIPPABLE. A separate void counter
    // beside `KeyPhase = _keys.WriteKeyPhase` could be deleted and every test would still
    // pass; folding the two together means a plan cannot get its phase without being counted.
    private bool ProtectOneMoreApplicationPacket()
    {
        ApplicationPacketsProtectedWithCurrentKeys++;
        return _keys.WriteKeyPhase;
    }
}
